spmv:
	gcc -O3 -I/opt/intel/oneapi/mkl/2022.2.0/include -I ../include/ -fopenmp mkl_spmv.c -o mkl_spmv -lmkl_rt  -L/opt/intel/oneapi/mkl/2022.2.0/lib/intel64/  -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl
